name: tests

# Controls when the action will run. 
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    strategy:
      matrix:
        bats_version: ['v1.2.1', 'v1.3.0', 'v1.4.1', 'v1.5.0', 'v1.6.1', 'v1.7.0']
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/checkout@v3
        with:
          repository: bats-core/bats-core
          ref: ${{ matrix.bats_version }}
          path: bats-core
      - run: bash --version
      - run: bats-core/bin/bats test/